-- CUBE database schema
-- Target: Supabase Postgres
-- Scope:
-- 1. Internal restaurant orders
-- 2. Future external pickup orders
-- 3. Future invoice integration
-- Excludes:
-- - Printer integration
-- - Payment gateway/webhook processing logic

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.assign_payment_event_hash()
returns trigger
language plpgsql
as $$
declare
  prior_hash text;
begin
  -- Serialise the hash chain when multiple iPads submit a payment simultaneously.
  perform pg_advisory_xact_lock(hashtext('cube_payment_event_chain'));

  select event_hash into prior_hash
  from public.payment_events
  order by fiscal_sequence desc
  limit 1;

  new.previous_event_hash := prior_hash;
  new.event_hash := encode(
    digest(
      concat_ws('|', new.fiscal_sequence::text, new.order_id::text, new.event_type,
        new.payment_method, new.amount::text, new.currency,
        coalesce(new.terminal_reference, ''), coalesce(new.reason, ''),
        new.recorded_by, new.recorded_at::text, coalesce(prior_hash, '')),
      'sha256'
    ),
    'hex'
  );
  return new;
end;
$$;

create or replace function public.prevent_financial_record_change()
returns trigger
language plpgsql
as $$
begin
  raise exception 'Financial records are append-only; create a reversal or refund event instead';
end;
$$;

create or replace function public.require_open_cash_register_day()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1 from public.cash_register_days as cash_day
    where cash_day.business_date = current_date and cash_day.status = 'open'
  ) then
    raise exception 'Cash register is not open for today';
  end if;
  return new;
end;
$$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  source text not null check (source in ('internal', 'online_pickup', 'online_paid')),
  channel text not null default 'staff' check (channel in ('staff', 'web', 'phone', 'walk_in')),
  order_status text not null default 'new'
    check (order_status in ('new', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled')),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid', 'pay_on_pickup', 'paid', 'failed', 'refunded')),
  customer_name text not null,
  customer_phone text,
  customer_address text,
  customer_notes text,
  internal_notes text,
  fulfillment_type text not null default 'pickup'
    check (fulfillment_type in ('pickup', 'dine_in', 'delivery')),
  scheduled_for timestamptz,
  subtotal_amount numeric(10,2) not null default 0,
  tax_amount numeric(10,2) not null default 0,
  total_amount numeric(10,2) not null default 0,
  currency text not null default 'EUR',
  invoice_needed boolean not null default false,
  invoice_id uuid,
  created_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_order_status on public.orders (order_status);
create index if not exists idx_orders_payment_status on public.orders (payment_status);
create index if not exists idx_orders_source on public.orders (source);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  sort_order integer not null default 0,
  item_name text not null,
  item_category text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  tax_rate numeric(5,2) not null default 10.00 check (tax_rate >= 0),
  total_price numeric(10,2) generated always as (round((quantity * unit_price)::numeric, 2)) stored,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_items_order_id on public.order_items (order_id);

-- Fiscal cash-register ledger. Payment and refund entries are append-only: corrections
-- must be represented by a new reversal/refund entry, never by editing a past entry.
create table if not exists public.payment_events (
  id uuid primary key default gen_random_uuid(),
  fiscal_sequence bigint generated by default as identity unique not null,
  order_id uuid not null references public.orders(id) on delete restrict,
  event_type text not null check (event_type in ('payment', 'refund', 'void')),
  payment_method text not null check (payment_method in ('cash', 'card', 'meal_voucher', 'other')),
  amount numeric(10,2) not null check (amount > 0),
  currency text not null default 'EUR',
  terminal_reference text,
  reason text,
  recorded_by text not null,
  recorded_at timestamptz not null default timezone('utc', now()),
  previous_event_hash text,
  event_hash text not null
);

create index if not exists idx_payment_events_order_id on public.payment_events (order_id, recorded_at);
create index if not exists idx_payment_events_recorded_at on public.payment_events (recorded_at desc);

create table if not exists public.cashier_audit_logs (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  entity_type text not null,
  entity_id uuid,
  actor text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_cashier_audit_logs_created_at on public.cashier_audit_logs (created_at desc);
create index if not exists idx_cashier_audit_logs_entity on public.cashier_audit_logs (entity_type, entity_id);

create table if not exists public.cash_register_days (
  business_date date primary key,
  status text not null default 'open' check (status in ('open', 'closed')),
  opening_cash numeric(10,2) not null default 0 check (opening_cash >= 0),
  expected_cash numeric(10,2),
  counted_cash numeric(10,2),
  variance_cash numeric(10,2),
  opened_by text not null,
  opened_at timestamptz not null default timezone('utc', now()),
  closed_by text,
  closed_at timestamptz,
  closing_hash text,
  notes text
);

alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders add constraint orders_payment_status_check
  check (payment_status in ('unpaid', 'pay_on_pickup', 'partial', 'paid', 'failed', 'refunded'));

drop trigger if exists trg_payment_events_integrity on public.payment_events;
create trigger trg_payment_events_integrity
before insert on public.payment_events
for each row
execute function public.assign_payment_event_hash();

drop trigger if exists trg_payment_events_require_open_day on public.payment_events;
create trigger trg_payment_events_require_open_day
before insert on public.payment_events
for each row
execute function public.require_open_cash_register_day();

drop trigger if exists trg_payment_events_immutable on public.payment_events;
create trigger trg_payment_events_immutable
before update or delete on public.payment_events
for each row
execute function public.prevent_financial_record_change();

drop trigger if exists trg_cashier_audit_logs_immutable on public.cashier_audit_logs;
create trigger trg_cashier_audit_logs_immutable
before update or delete on public.cashier_audit_logs
for each row
execute function public.prevent_financial_record_change();

create table if not exists public.invoice_clients (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  legal_name text,
  address_line_1 text not null,
  address_line_2 text,
  postal_code text,
  city text not null,
  country text not null default 'France',
  vat_number text,
  contact_name text,
  contact_email text,
  contact_phone text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_invoice_clients_company_name on public.invoice_clients (company_name);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  order_id uuid references public.orders(id) on delete set null,
  invoice_client_id uuid references public.invoice_clients(id) on delete set null,
  issue_date timestamptz not null default timezone('utc', now()),
  due_date timestamptz,
  payment_method text,
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid', 'paid', 'partial', 'cancelled', 'refunded')),
  subtotal_amount numeric(10,2) not null default 0,
  tax_amount numeric(10,2) not null default 0,
  total_amount numeric(10,2) not null default 0,
  currency text not null default 'EUR',
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_invoices_order_id on public.invoices (order_id);
create index if not exists idx_invoices_issue_date on public.invoices (issue_date desc);

create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  sort_order integer not null default 0,
  description text not null,
  quantity integer not null check (quantity > 0),
  unit_price_ht numeric(10,2) not null check (unit_price_ht >= 0),
  tax_rate numeric(5,2) not null default 10.00 check (tax_rate >= 0),
  unit_price_ttc numeric(10,2) not null check (unit_price_ttc >= 0),
  total_price_ttc numeric(10,2) generated always as (round((quantity * unit_price_ttc)::numeric, 2)) stored,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_invoice_items_invoice_id on public.invoice_items (invoice_id);

alter table public.orders
  add constraint fk_orders_invoice
  foreign key (invoice_id) references public.invoices(id) on delete set null;

create table if not exists public.daily_counters (
  counter_name text not null,
  counter_date text not null,
  last_value integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (counter_name, counter_date)
);

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

drop trigger if exists trg_invoice_clients_updated_at on public.invoice_clients;
create trigger trg_invoice_clients_updated_at
before update on public.invoice_clients
for each row
execute function public.set_updated_at();

drop trigger if exists trg_invoices_updated_at on public.invoices;
create trigger trg_invoices_updated_at
before update on public.invoices
for each row
execute function public.set_updated_at();

drop trigger if exists trg_daily_counters_updated_at on public.daily_counters;
create trigger trg_daily_counters_updated_at
before update on public.daily_counters
for each row
execute function public.set_updated_at();

create or replace function public.next_daily_counter(counter_name_input text, counter_date_input text)
returns integer
language plpgsql
as $$
declare
  next_value integer;
begin
  insert into public.daily_counters (counter_name, counter_date, last_value)
  values (counter_name_input, counter_date_input, 1)
  on conflict (counter_name, counter_date)
  do update
    set last_value = public.daily_counters.last_value + 1,
        updated_at = timezone('utc', now())
  returning last_value into next_value;

  return next_value;
end;
$$;

create or replace function public.generate_order_number()
returns text
language plpgsql
as $$
declare
  current_date_part text;
  next_sequence integer;
begin
  current_date_part := to_char(timezone('utc', now()), 'YYYYMMDD');
  next_sequence := public.next_daily_counter('order', current_date_part);

  return current_date_part || '-' || lpad(next_sequence::text, 3, '0');
end;
$$;

create or replace function public.assign_order_number()
returns trigger
language plpgsql
as $$
begin
  if new.order_number is null or btrim(new.order_number) = '' then
    new.order_number := public.generate_order_number();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_orders_assign_number on public.orders;
create trigger trg_orders_assign_number
before insert on public.orders
for each row
execute function public.assign_order_number();

create or replace function public.generate_invoice_number()
returns text
language plpgsql
as $$
declare
  current_date_part text;
  next_sequence integer;
begin
  current_date_part := to_char(timezone('utc', now()), 'YYYYMMDD');
  next_sequence := public.next_daily_counter('invoice', current_date_part);

  return 'FAC-' || current_date_part || '-' || lpad(next_sequence::text, 3, '0');
end;
$$;

create or replace function public.assign_invoice_number()
returns trigger
language plpgsql
as $$
begin
  if new.invoice_number is null or btrim(new.invoice_number) = '' then
    new.invoice_number := public.generate_invoice_number();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_invoices_assign_number on public.invoices;
create trigger trg_invoices_assign_number
before insert on public.invoices
for each row
execute function public.assign_invoice_number();

create or replace function public.create_invoice_with_items(invoice_payload jsonb, item_payloads jsonb)
returns table (
  id uuid,
  invoice_number text,
  total_amount numeric
)
language plpgsql
as $$
declare
  created_invoice public.invoices%rowtype;
  linked_order_id uuid;
begin
  insert into public.invoices (
    order_id,
    invoice_client_id,
    issue_date,
    due_date,
    payment_method,
    payment_status,
    subtotal_amount,
    tax_amount,
    total_amount,
    currency,
    notes
  )
  values (
    nullif(invoice_payload->>'order_id', '')::uuid,
    nullif(invoice_payload->>'invoice_client_id', '')::uuid,
    coalesce((invoice_payload->>'issue_date')::timestamptz, timezone('utc', now())),
    nullif(invoice_payload->>'due_date', '')::timestamptz,
    nullif(invoice_payload->>'payment_method', ''),
    coalesce(invoice_payload->>'payment_status', 'paid'),
    coalesce((invoice_payload->>'subtotal_amount')::numeric, 0),
    coalesce((invoice_payload->>'tax_amount')::numeric, 0),
    coalesce((invoice_payload->>'total_amount')::numeric, 0),
    coalesce(invoice_payload->>'currency', 'EUR'),
    nullif(invoice_payload->>'notes', '')
  )
  returning * into created_invoice;

  insert into public.invoice_items (
    invoice_id,
    sort_order,
    description,
    quantity,
    unit_price_ht,
    tax_rate,
    unit_price_ttc
  )
  select
    created_invoice.id,
    coalesce((item->>'sort_order')::integer, 0),
    item->>'description',
    (item->>'quantity')::integer,
    (item->>'unit_price_ht')::numeric,
    coalesce((item->>'tax_rate')::numeric, 10.00),
    (item->>'unit_price_ttc')::numeric
  from jsonb_array_elements(item_payloads) as item;

  linked_order_id := nullif(invoice_payload->>'order_id', '')::uuid;
  if linked_order_id is not null then
    update public.orders
    set invoice_id = created_invoice.id
    where public.orders.id = linked_order_id;
  end if;

  return query
  select created_invoice.id, created_invoice.invoice_number, created_invoice.total_amount;
end;
$$;

create or replace function public.create_order_with_items(order_payload jsonb, item_payloads jsonb)
returns table (
  id uuid,
  order_number text,
  total_amount numeric
)
language plpgsql
as $$
declare
  created_order public.orders%rowtype;
begin
  insert into public.orders (
    source,
    channel,
    order_status,
    payment_status,
    customer_name,
    customer_phone,
    customer_address,
    customer_notes,
    fulfillment_type,
    subtotal_amount,
    tax_amount,
    total_amount,
    currency
  )
  values (
    coalesce(order_payload->>'source', 'online_pickup'),
    coalesce(order_payload->>'channel', 'web'),
    coalesce(order_payload->>'order_status', 'new'),
    coalesce(order_payload->>'payment_status', 'pay_on_pickup'),
    order_payload->>'customer_name',
    nullif(order_payload->>'customer_phone', ''),
    nullif(order_payload->>'customer_address', ''),
    nullif(order_payload->>'customer_notes', ''),
    coalesce(order_payload->>'fulfillment_type', 'pickup'),
    coalesce((order_payload->>'subtotal_amount')::numeric, 0),
    coalesce((order_payload->>'tax_amount')::numeric, 0),
    coalesce((order_payload->>'total_amount')::numeric, 0),
    coalesce(order_payload->>'currency', 'EUR')
  )
  returning * into created_order;

  insert into public.order_items (
    order_id,
    sort_order,
    item_name,
    item_category,
    quantity,
    unit_price,
    tax_rate,
    notes
  )
  select
    created_order.id,
    coalesce((item->>'sort_order')::integer, 0),
    item->>'item_name',
    nullif(item->>'item_category', ''),
    (item->>'quantity')::integer,
    (item->>'unit_price')::numeric,
    coalesce((item->>'tax_rate')::numeric, 10.00),
    nullif(item->>'notes', '')
  from jsonb_array_elements(item_payloads) as item;

  return query
  select created_order.id, created_order.order_number, created_order.total_amount;
end;
$$;

-- The only supported path for recording a cashier payment or refund. It locks the
-- order row, appends one immutable fiscal event, and records an audit entry atomically.
create or replace function public.record_payment_event(payment_payload jsonb)
returns table (
  payment_event_id uuid,
  payment_status text,
  paid_amount numeric
)
language plpgsql
as $$
declare
  target_order_id uuid := (payment_payload->>'order_id')::uuid;
  target_event_type text := payment_payload->>'event_type';
  target_method text := payment_payload->>'payment_method';
  target_amount numeric := (payment_payload->>'amount')::numeric;
  target_actor text := payment_payload->>'recorded_by';
  order_total numeric;
  prior_paid numeric;
  resulting_paid numeric;
  resulting_status text;
  created_event public.payment_events%rowtype;
begin
  if target_event_type not in ('payment', 'refund', 'void')
    or target_method not in ('cash', 'card', 'meal_voucher', 'other')
    or target_amount is null or target_amount <= 0
    or target_actor is null or btrim(target_actor) = '' then
    raise exception 'Invalid payment event';
  end if;

  select total_amount into order_total
  from public.orders where id = target_order_id for update;
  if not found then
    raise exception 'Order not found';
  end if;

  select coalesce(sum(case when event_type = 'payment' then amount else -amount end), 0)
  into prior_paid from public.payment_events where order_id = target_order_id;

  if target_event_type = 'payment' then
    if prior_paid + target_amount > order_total then
      raise exception 'Payment exceeds order total';
    end if;
    resulting_paid := prior_paid + target_amount;
  else
    if target_amount > prior_paid then
      raise exception 'Refund exceeds recorded payments';
    end if;
    resulting_paid := prior_paid - target_amount;
  end if;

  insert into public.payment_events (
    order_id, event_type, payment_method, amount, currency, terminal_reference,
    reason, recorded_by
  ) values (
    target_order_id, target_event_type, target_method, target_amount,
    coalesce(payment_payload->>'currency', 'EUR'),
    nullif(payment_payload->>'terminal_reference', ''),
    nullif(payment_payload->>'reason', ''), target_actor
  ) returning * into created_event;

  resulting_status := case
    when resulting_paid = order_total then 'paid'
    when resulting_paid = 0 and target_event_type in ('refund', 'void') then 'refunded'
    when resulting_paid > 0 then 'partial'
    else 'unpaid'
  end;

  update public.orders set payment_status = resulting_status where id = target_order_id;
  insert into public.cashier_audit_logs (event_type, entity_type, entity_id, actor, details)
  values (
    target_event_type, 'payment_event', created_event.id, target_actor,
    jsonb_build_object('order_id', target_order_id, 'amount', target_amount,
      'payment_method', target_method, 'fiscal_sequence', created_event.fiscal_sequence)
  );

  return query select created_event.id, resulting_status, resulting_paid;
end;
$$;

create or replace function public.close_cash_register_day(close_payload jsonb)
returns table (business_date date, expected_cash numeric, counted_cash numeric, variance_cash numeric)
language plpgsql
as $$
declare
  target_date date := coalesce((close_payload->>'business_date')::date, current_date);
  target_counted numeric := (close_payload->>'counted_cash')::numeric;
  target_actor text := close_payload->>'closed_by';
  calculated_cash numeric;
begin
  if target_counted is null or target_counted < 0 or target_actor is null or btrim(target_actor) = '' then
    raise exception 'Invalid daily closure';
  end if;

  select coalesce(sum(case when event_type = 'payment' and payment_method = 'cash' then amount
                           when event_type in ('refund', 'void') and payment_method = 'cash' then -amount else 0 end), 0)
  into calculated_cash
  from public.payment_events
  where recorded_at::date = target_date;

  insert into public.cash_register_days (business_date, opening_cash, opened_by)
  values (target_date, 0, target_actor)
  on conflict on constraint cash_register_days_pkey do nothing;

  update public.cash_register_days as cash_day
  set status = 'closed', expected_cash = opening_cash + calculated_cash,
      counted_cash = target_counted, variance_cash = target_counted - (opening_cash + calculated_cash),
      closed_by = target_actor, closed_at = timezone('utc', now()),
      closing_hash = encode(digest(concat_ws('|', target_date::text, calculated_cash::text, target_counted::text, target_actor), 'sha256'), 'hex')
  where cash_day.business_date = target_date and cash_day.status = 'open'
  returning cash_day.expected_cash, cash_day.counted_cash, cash_day.variance_cash
  into expected_cash, counted_cash, variance_cash;

  if not found then raise exception 'Business day is already closed'; end if;
  insert into public.cashier_audit_logs (event_type, entity_type, actor, details)
  values ('daily_close', 'cash_register_day', target_actor, jsonb_build_object('business_date', target_date, 'expected_cash', expected_cash, 'counted_cash', counted_cash, 'variance_cash', variance_cash));
  business_date := target_date;
  return next;
end;
$$;

create or replace function public.open_cash_register_day(open_payload jsonb)
returns table (business_date date, opening_cash numeric)
language plpgsql
as $$
declare
  target_date date := coalesce((open_payload->>'business_date')::date, current_date);
  target_opening numeric := (open_payload->>'opening_cash')::numeric;
  target_actor text := open_payload->>'opened_by';
begin
  if target_opening is null or target_opening < 0 or target_actor is null or btrim(target_actor) = '' then raise exception 'Invalid opening'; end if;
  insert into public.cash_register_days (business_date, opening_cash, opened_by)
  values (target_date, target_opening, target_actor)
  on conflict on constraint cash_register_days_pkey do nothing;
  if not found then raise exception 'Business day is already open or closed'; end if;
  insert into public.cashier_audit_logs (event_type, entity_type, actor, details)
  values ('daily_open', 'cash_register_day', target_actor, jsonb_build_object('business_date', target_date, 'opening_cash', target_opening));
  business_date := target_date; opening_cash := target_opening; return next;
end;
$$;

create or replace view public.order_summary as
select
  o.id,
  o.order_number,
  o.source,
  o.channel,
  o.order_status,
  o.payment_status,
  o.customer_name,
  o.customer_phone,
  o.customer_address,
  o.customer_notes,
  o.fulfillment_type,
  o.scheduled_for,
  o.subtotal_amount,
  o.tax_amount,
  o.total_amount,
  o.currency,
  o.invoice_needed,
  o.created_at,
  o.updated_at,
  coalesce(
    json_agg(
      json_build_object(
        'id', oi.id,
        'name', oi.item_name,
        'category', oi.item_category,
        'qty', oi.quantity,
        'price', oi.unit_price,
        'tax_rate', oi.tax_rate,
        'total', oi.total_price,
        'notes', oi.notes,
        'sort_order', oi.sort_order
      )
      order by oi.sort_order, oi.created_at
    ) filter (where oi.id is not null),
    '[]'::json
  ) as items
from public.orders o
left join public.order_items oi on oi.order_id = o.id
group by o.id;
